name = "Conductor"
uuid = "d194a933-43b5-4953-818b-974a45c81e67"
authors = ["Wiktor Phillips <wsphillips@gmail.com>"]
version = "0.0.1"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
IfElse = "0.1.0"
ModelingToolkit = "5.22"
Setfield = "0.7.0"
SymbolicUtils = "0.13.1"
Symbolics = "1.4"
Unitful = "1.8"
julia = "1.5"
