name = "Conductor"
uuid = "d194a933-43b5-4953-818b-974a45c81e67"
authors = ["Wiktor Phillips <wsphillips@gmail.com>"]
version = "0.0.5"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Distributions = "0.25"
DocStringExtensions = "0.8"
Graphs = "1"
MacroTools = "0.5"
ModelingToolkit = "8.21"
SciMLBase = "1.47"
Setfield = "0.8,1"
SymbolicUtils = "0.19"
Symbolics = "4"
Unitful = "1"
julia = "1.8"
