[deps]
Conductor = "d194a933-43b5-4953-818b-974a45c81e67"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
